project:
  type: website

website:
  title: "kbay_habitat_mapping Lab Notebook"
  navbar:
    left:
      - file: index.qmd
      - file: entries/

format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
